### PR TITLE
doc fix: Claim what actually happens in the code

### PR DESCRIPTION
**Pull request by unkaktus**

### CODE REVIEW

**Review by tadukurow — APPROVED** [review]

**Comment by unkaktus** [comment]
ok?

**Comment by fmpwizard** [comment]
If you close and reopen the PR, travis will rerun this build and thanks to  https://github.com/go-mgo/mgo/pull/462 , your PR should pass all tests on all mongodb versions (even though this is just a doc fix that didn't touch any code)

**Comment by niemeyer** [comment]
The documentation is right. The < 0 is an implementation detail and can change, breaking the code if one doesn't follow the documentation.

**Comment by unkaktus** [comment]
Is is not an implementation detail because it defines behavior of the exported function.  What happens if timeout is set to `-2`?

**Pull request closed without merging**
