### PR TITLE
Session.IsDup for *bulkError by underlying error

### PR DESCRIPTION
**Pull request by ek220**
Session.IsDup for *bulkError by recursion using underlying err

### CODE REVIEW

**Comment by niemeyer** [comment]
Thanks, sounds reasonable.

Can we please have a test for this?

**Comment by ek220** [comment]
Added asserts to bulk tests
Testing the IsDup directly is impossible due to bulkError is private

-- Eugeny

**Comment by niemeyer** [comment]
Okay, that sounds fine. There's a small question here, though. What is the semantics of IsDup when one of the errors is a dup but the other is not?

**Comment by ek220** [comment]
At the moment bulkError is container for single error.
For single error IsDup is applicable. 

The possible solution to provide array contains an error document for each write operation that errors.
http://docs.mongodb.org/manual/reference/method/BulkWriteResult/#BulkWriteResult

**Comment by niemeyer** [comment]
The reason bulkError is not exposed is precisely because it is not yet representing everything it needs to for bulk scenarios. If the idea was to have a single error always, it wouldn't make sense to wrap it in such a way.

**Comment by niemeyer** [comment]
Maybe we need something along the lines of `BulkError.Has` or `BulkError.Contains`, which takes a predicate function of the `IsDup` style. Another option would be to say that such standard predicates return true if any one of the errors match, which doesn't smell so great, but maybe it's the useful thing to do. We need to think through what would be the correct way to handle such multi-error cases.. what will we want to do when we have one of these at hand?

**Comment by niemeyer** [comment]
After sleeping on this, we should make IsDup return true when all errors in a bulk update are dup errors, which means it would be fine to make IsDup return true when there's on a single error and that error is a dup error. That seems like the most useful and safe approach.

**Comment by ek220** [comment]
Need more investigations

**Comment by niemeyer** [comment]
Why? I was tempted to adopt your suggestion, for the reason exposed above.

**Pull request closed without merging**
