### PR TITLE
Adding support for $maxTimeMS on queries

### PR DESCRIPTION
**Pull request by minyoung**
Relevant documentation:
http://blog.mongodb.org/post/83621787773/maxtimems-and-query-optimizer-introspection-in
http://docs.mongodb.org/master/reference/method/cursor.maxTimeMS/

### CODE REVIEW

**Comment by minyoung** [comment]
Any comments/feedback?

**Comment by dynamike** [comment]
Would love to see this merged. Anything holding it up?

**Comment by charity** [comment]
Yes please!!  We are waiting on this.  :)

**Comment by niemeyer** [comment]
Next version is coming in the next couple of days. Something along these lines will be in. Will probably take your patch and tweak for usual conventions.

**Pull request merged**
