### PR TITLE
Add build tag to make sure sasl.c isn't built on windows

### PR DESCRIPTION
**Pull request by vkarpov15**

### CODE REVIEW

**Comment by vkarpov15** [comment]
Also fixed an [incorrect authentication mechanism name](http://docs.mongodb.org/manual/core/authentication/#authentication-mechanisms)

**Comment by niemeyer** [comment]
Thanks for the build fix, happy to apply it.

That said, we cannot apply the suggested rename as-is. People out there are likely depending on this name, and it was modified in the server right before the 2.4 release:

```
https://jira.mongodb.org/browse/SERVER-8501
```

We should support the two names instead.

To avoid another roundtrip, I have applied the two fixes to v2-dev. Thanks again for the changes.

**Comment by vkarpov15** [comment]
@niemeyer I unfortunately don't see the MONGODB-CR change in v2-dev. Would go a long way to getting our tools back on the main driver and off of our fork :)

**Comment by niemeyer** [comment]
Sorry, it was late and I forgot to push it. Should be there now.

**Pull request closed without merging**
