### PR TITLE
Support encoding byte arrays in structs

### LINKED ISSUE #73: Cannot encode byte arrays
I have a struct that looks like this
```go
type Handle struct {
    Hash [32]byte
}
```

When I try to encode it with bson, I get "reflect.Value.Slice: slice of unaddressable array" coming from https://github.com/go-mgo/mgo/blob/v2/bson/encode.go#L368. In that code, if v is not addressable it can be copied to a slice and then added as binary, so it looks like the following (which works):

```go
if v.CanAddr() {
	e.addBinary('\x00', v.Slice(0, v.Len()).Interface().([]byte))
} else {
	slice := reflect.MakeSlice(reflect.SliceOf(v.Type().Elem()), v.Len(), v.Len())
	reflect.Copy(slice, v)
	e.addBinary('\x00', slice.Interface().([]byte))
}
```

I can submit a pull request, but it would help if someone explained where I should add tests for this case in `bson_test.go`.

### PR DESCRIPTION
**Pull request by tchajed**
Fix #73.

### CODE REVIEW

**Comment by niemeyer** [comment]
I'm still on the fence about this one. It feels surprisingly costly for such a trivial operation.

**Comment by tchajed** [comment]
The problem is that if CanAddr() returns false, you can't address the array's memory. This makes it tricky to pass the bytes in the array to the encoder; since Go doesn't have generics, you can't write a method that takes an arbitrary array, it has to take a slice, and there's no way to get a zero-copy slice in this case.

One way around the copy is to instead pass the bytes individually to the encoder. This will have a high reflection overhead, since you'll have to call `(v Value) Index()` and convert each `reflect.Value` to a byte.

I agree that a copy seems unnecessary, but it's better than one reflection conversion per byte or leaving the bug there.

**Comment by niemeyer** [comment]
The trade-off doesn't seem so clear to me as it is to you. You see it as a bug, and I see it as a feature explicitly left out for lack of a reasonable way to handle it. Requiring 3000 allocations to encode 1000 values which contain 3 arrays with a couple of integers each sounds bad, even ignoring the fact that they need to be copied. The impact is disproportional to the expectation of what such an operation would do.

I'm not rulling it out yet, but it's not so straightforward a choice to me.

**Comment by tchajed** [comment]
I checked what encoding/json does and it's actually the other option I suggested (access each element as a `reflect.Value` and then get the element). This will be slower but won't cause another memory allocation.

**Comment by niemeyer** [comment]
Okay, I'd be happier about that implementation as well.

**Comment by tchajed** [comment]
Cool, implemented that in pull #110.

**Pull request closed without merging**
